name: xpublish_env_default
channels:
  - defaults
  - conda-forge
dependencies:
- cachey
- dask
- fastapi>=0.78.0
- numcodecs
- numpy<2
- pluggy
- toolz
- uvicorn
- xarray!=v2023.09.0  # see https://github.com/xpublish-community/xpublish/issues/237
- zarr<3
- xpublish
- matplotlib
- python-dotenv